INSERT INTO "Team" ("name", "logoUrl") VALUES ('Al Ahly', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Al_Ahly_SC_logo.png/1200px-Al_Ahly_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Zamalek', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Zamalek_SC.png/1200px-Zamalek_SC.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Pyramids FC', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Pyramids_FC_logo.png/1200px-Pyramids_FC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Ismaily', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Ismaily_SC_logo.png/1200px-Ismaily_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Al Masry', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Al_Masry_SC_logo.png/1200px-Al_Masry_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('El Gouna', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/El_Gouna_FC_logo.png/1200px-El_Gouna_FC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('ENPPI', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/ENPPI_SC_logo.png/1200px-ENPPI_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Ghazl El Mahalla', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Ghazl_El_Mahalla_SC_logo.png/1200px-Ghazl_El_Mahalla_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Misr Lel Makkasa', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/Misr_Lel_Makkasa_SC_logo.png/1200px-Misr_Lel_Makkasa_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Smouha', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Smouha_SC_logo.png/1200px-Smouha_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Wadi Degla', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Wadi_Degla_SC_logo.png/1200px-Wadi_Degla_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('El Entag El Harby', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/El_Entag_El_Harby_SC_logo.png/1200px-El_Entag_El_Harby_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('National Bank of Egypt', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/National_Bank_of_Egypt_SC_logo.png/1200px-National_Bank_of_Egypt_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Ceramica Cleopatra', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Ceramica_Cleopatra_SC_logo.png/1200px-Ceramica_Cleopatra_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Al Ittihad Alexandria', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Al_Ittihad_Alexandria_SC_logo.png/1200px-Al_Ittihad_Alexandria_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Aswan', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Aswan_SC_logo.png/1200px-Aswan_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('El Mokawloon', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/El_Mokawloon_SC_logo.png/1200px-El_Mokawloon_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('El Sharkia', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/El_Sharkia_SC_logo.png/1200px-El_Sharkia_SC_logo.png');
INSERT INTO "Team" ("name", "logoUrl") VALUES ('Talaea El Gaish', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Tala%27ea_El_Gaish_SC_logo.png/1200px-Tala%27ea_El_Gaish_SC_logo.png');
